// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarReverieCore;

#nullable disable

namespace StarReverieCore.Migrations
{
    [DbContext(typeof(StarReverieDbContext))]
    [Migration("20250727061536_MinHPAndStamina")]
    partial class MinHPAndStamina
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("StarReverieCore.Models.AttributeScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasicLift")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BasicMove")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Constitution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dodge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Encumbrance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinHP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Perception")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Speed")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stamina")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Will")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XP")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("AttributeScores");
                });

            modelBuilder.Entity("StarReverieCore.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("StarReverieCore.Models.DialogueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ParentDialogueId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpeakerDialogue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpeakerLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentDialogueId");

                    b.ToTable("Dialogues");
                });

            modelBuilder.Entity("StarReverieCore.Models.SkillModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Skill")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("StarReverieCore.Models.WeaponModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Accuracy")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AmmoWeight")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bulk")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentAmmo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DamageType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAmmo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Range")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoF")
                        .HasColumnType("INTEGER");

                    b.Property<int>("STRRequirement")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SkillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WeaponWeight")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("SkillId");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("StarReverieCore.Models.AttributeScore", b =>
                {
                    b.HasOne("StarReverieCore.Models.Character", "Character")
                        .WithOne("AttributeScore")
                        .HasForeignKey("StarReverieCore.Models.AttributeScore", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("StarReverieCore.Models.DialogueModel", b =>
                {
                    b.HasOne("StarReverieCore.Models.DialogueModel", "ParentDialogue")
                        .WithMany("Responses")
                        .HasForeignKey("ParentDialogueId");

                    b.Navigation("ParentDialogue");
                });

            modelBuilder.Entity("StarReverieCore.Models.SkillModel", b =>
                {
                    b.HasOne("StarReverieCore.Models.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("StarReverieCore.Models.WeaponModel", b =>
                {
                    b.HasOne("StarReverieCore.Models.Character", "Character")
                        .WithOne("Weapon")
                        .HasForeignKey("StarReverieCore.Models.WeaponModel", "CharacterId");

                    b.HasOne("StarReverieCore.Models.SkillModel", "SkillModel")
                        .WithMany("Weapons")
                        .HasForeignKey("SkillId");

                    b.Navigation("Character");

                    b.Navigation("SkillModel");
                });

            modelBuilder.Entity("StarReverieCore.Models.Character", b =>
                {
                    b.Navigation("AttributeScore")
                        .IsRequired();

                    b.Navigation("Skills");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("StarReverieCore.Models.DialogueModel", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("StarReverieCore.Models.SkillModel", b =>
                {
                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
